name: HACS Validation

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    name: Validate repository with HACS
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"
